AnyImageKit/AnyImageKit

AnyImageKit.xcodeproj/project.pbxproj, AnyImageKit.xcodeproj/xcshareddata/xcschemes/Example.xcscheme, README.md, README_CN.md, Sources/Capture/Controller/CaptureViewController.swift, Sources/Capture/Shader/PassThrough.metal, Sources/Capture/Util/Capture.swift, Sources/Capture/Util/VideoIOComponent.swift, Sources/Capture/View/CapturePreviewContentView.swift, Sources/Capture/View/CapturePreviewView.swift, Sources/Editor/Controller/VideoEditorController.swift
- 修复老设备上画面不跟手的问题
- 完全使用 Metal 进行纹理绘制
=> Fix capture stabilization

AnyImageKit.xcodeproj/project.pbxproj, Documentation/README_CN.md, Documentation/RELEASE_NOTE.md, Documentation/RELEASE_NOTE_CN.md, Documentation/Wiki/Capture使用说明.md, Documentation/Wiki/Editor使用说明.md, Documentation/Wiki/Home.md, Documentation/Wiki/Picker使用说明.md, Documentation/Wiki/slidebar.md, Documentation/Wiki/使用说明.md, Documentation/Wiki/安装说明.md, Example/Info.plist, README.md
=> Add Documentation

Documentation/RELEASE_NOTE.md, Documentation/RELEASE_NOTE_CN.md, Documentation/Wiki/Home.md, Documentation/Wiki/slidebar.md
=> Documentation

Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
=> fix: Picker can't scroll to end when switch album

Sources/AnyImageKit/Picker/Controller/AlbumPickerViewController.swift, Sources/AnyImageKit/Picker/Presentation/MenuDropDownPresentationController.swift
=> feat: scroll to current album

Example/Controller/Application/DisableCheckRuleViewController.swift, Sources/AnyImageKit/Editor/View/PhotoEditorContentView+Crop.swift, Sources/AnyImageKit/Editor/View/PhotoEditorContentView+Getter.swift, Sources/AnyImageKit/Editor/View/PhotoEditorContentView.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Controller/ImagePickerController.swift, Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift, Sources/AnyImageKit/Picker/View/Cell/PhotoPreviewCell.swift, Sources/AnyImageKit/Picker/View/Cell/PreviewCell.swift, Sources/AnyImageKit/Picker/View/PickerPreviewIndexView.swift
- Picker 预览和 Editor 中图片最大缩放比例从固定值改为根据图片尺寸计算
- 修复 Picker 预览 toolBar 颜色不同步问题
- 修复 Picker QuickPicker & DisableRule UI 展示错误问题
- 优化 DisableRule Example project
=> Update photo zoom scale

Sources/AnyImageKit/Picker/View/Cell/PhotoGIFPreviewCell.swift, Sources/AnyImageKit/Picker/View/Cell/PhotoLivePreviewCell.swift, Sources/AnyImageKit/Picker/View/Cell/PhotoPreviewCell.swift, Sources/AnyImageKit/Picker/View/Cell/VideoPreviewCell.swift
- 修复选中后设置 iCloud 进度时没有判断当前 asset 是否为请求时的 asset ，并整理优化代码
=> fix: set_icloud_progress

Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift
=> fix(Editor): 修复某些情况下马赛克无法使用的问题

AnyImageKit.podspec, Podfile.lock, Sources/AnyImageKit/Capture/View/CaptureFocusView.swift, Sources/AnyImageKit/Capture/View/CapturePreviewContentView.swift, Sources/AnyImageKit/Capture/View/CaptureToolView.swift, Sources/AnyImageKit/Core/Extension/Core+Bundle.swift, Sources/AnyImageKit/Core/Util/Common/BundleHelper.swift, Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift, Sources/AnyImageKit/Editor/Controller/VideoEditorController.swift, Sources/AnyImageKit/Editor/EditorOptionsInfo.swift, Sources/AnyImageKit/Editor/View/Photo/Kit/ColorWell.swift, Sources/AnyImageKit/Editor/View/Photo/Kit/TextImageView.swift, Sources/AnyImageKit/Editor/View/Photo/Kit/TextTrashView.swift, Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorCropToolView.swift, Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorEditOptionsView.swift, Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorMosaicToolView.swift, Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorPenToolView.swift, Sources/AnyImageKit/Editor/View/Photo/ToolBar/EditorTextToolView.swift, Sources/AnyImageKit/Editor/View/Video/VideoEditorCropProgressView.swift, Sources/AnyImageKit/Editor/View/Video/VideoEditorCropToolView.swift, Sources/AnyImageKit/Editor/View/Video/VideoEditorToolView.swift, Sources/AnyImageKit/Picker/View/Cell/AssetCell.swift, Sources/AnyImageKit/Picker/View/Cell/CameraCell.swift, Sources/AnyImageKit/Picker/View/Cell/VideoPreviewCell.swift, Sources/AnyImageKit/Picker/View/Kit/LivePhotoTipView.swift, Sources/AnyImageKit/Picker/View/Kit/LoadingiCloudView.swift, Sources/AnyImageKit/Picker/View/Kit/NumberCircleButton.swift, Sources/AnyImageKit/Picker/View/Kit/PickerArrowButton.swift, Sources/AnyImageKit/Picker/View/PermissionLimitedView.swift, Sources/AnyImageKit/Picker/View/PickerPreviewNavigationBar.swift
- fix metal library load in Swift Static Libraries mode when use CocoaPods #52 
- Improve image resource load for module
=> fix: static linkage

Sources/AnyImageKit/Editor/View/Photo/PhotoEditorContentView+Crop.swift
=> Fix input text

Sources/AnyImageKit/Capture/Controller/CaptureViewController.swift, Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift, Sources/AnyImageKit/Editor/Controller/VideoEditorController.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Controller/ImagePickerController.swift
=> Fix status bar style dose not work

Sources/AnyImageKit/Capture/Controller/CaptureViewController.swift, Sources/AnyImageKit/Capture/Controller/PadCaptureViewController.swift, Sources/AnyImageKit/Core/Controller/AnyImageViewController.swift, Sources/AnyImageKit/Core/Controller/HUDViewController.swift, Sources/AnyImageKit/Core/Util/Common/HUDHelper.swift, Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift, Sources/AnyImageKit/Editor/Controller/VideoEditorController.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Capture.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Editor.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Controller/ImagePickerController.swift, Sources/AnyImageKit/Picker/Controller/PhotoPreviewController+Editor.swift
=> Imporve HUD status bar

AnyImageKit.xcodeproj/project.pbxproj, Sources/AnyImageKit/Picker/Model/Album.swift, Sources/AnyImageKit/Picker/Model/Asset.swift, Sources/AnyImageKit/Picker/Model/IdentifiableResource.swift
add `IdentifiableResource`, prepare for image browser
=> feat: add IdentifiableResource

Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Editor.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift, Sources/AnyImageKit/Picker/Model/Asset.swift, Sources/AnyImageKit/Picker/Model/AssetDisableCheckRule.swift, Sources/AnyImageKit/Picker/View/Cell/AssetCell.swift, Sources/AnyImageKit/Resources/Picker/en.lproj/Picker.strings, Sources/AnyImageKit/Resources/Picker/pt-BR.lproj/Picker.strings, Sources/AnyImageKit/Resources/Picker/tr.lproj/Picker.strings, Sources/AnyImageKit/Resources/Picker/zh-Hans.lproj/Picker.strings
Add selected asset in disable rule
=> Disable rule

Podfile.lock, Sources/AnyImageKit/Editor/View/Video/VideoPreview.swift
=> fix: check CMTime.isValid before set video pregress

Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Editor.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Controller/PhotoPreviewController+Editor.swift
Fix cannot display camera icon;
Fix picker can edit GIF and LivePhoto;
=> Fix Picker display bug

AnyImageKit.xcodeproj/project.pbxproj, Sources/AnyImageKit/Capture/Controller/CaptureViewController.swift, Sources/AnyImageKit/Capture/Util/DataTrack/Capture+AnyImageEvent.swift, Sources/AnyImageKit/Capture/Util/DataTrack/Capture+AnyImagePage.swift, Sources/AnyImageKit/Core/Controller/AnyImageViewController.swift, Sources/AnyImageKit/Core/Util/DataTrack/AnyImageEvent.swift, Sources/AnyImageKit/Core/Util/DataTrack/AnyImagePage.swift, Sources/AnyImageKit/Editor/Controller/InputTextViewController.swift, Sources/AnyImageKit/Editor/Controller/PhotoEditorController.swift, Sources/AnyImageKit/Editor/Controller/VideoEditorController.swift, Sources/AnyImageKit/Editor/EditorTheme.swift, Sources/AnyImageKit/Editor/Util/DataTrack/Editor+AnyImageEvent.swift, Sources/AnyImageKit/Editor/Util/DataTrack/Editor+AnyImagePage.swift, Sources/AnyImageKit/Editor/View/Video/VideoEditorCropToolView.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Capture.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Controller/PhotoPreviewController+Editor.swift, Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift, Sources/AnyImageKit/Picker/PickerTheme.swift, Sources/AnyImageKit/Picker/Util/DataTrack/Picker+AnyImageEvent.swift, Sources/AnyImageKit/Picker/Util/DataTrack/Picker+AnyImagePage.swift, Sources/AnyImageKit/Picker/View/PermissionDeniedView.swift
=> Improve data track

AnyImageKit.podspec, Podfile.lock, Sources/AnyImageKit/Picker/Util/PickerManager+Album.swift
Details can be found here https://github.com/AnyImageProject/AnyImageKit/issues/128
=> Fix shared album list and bump version

Sources/AnyImageKit/Picker/Controller/AssetPickerViewController+Capture.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift, Sources/AnyImageKit/Picker/Model/Asset.swift, Sources/AnyImageKit/Picker/Util/PickerManager.swift
The disable rule is not checked when selecting photos after taking photos.
=> Fix picker

AnyImageKit.podspec, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift
1. fixed xcode 14 build error
2. iOS support
=> fixed xcode14 build error && iOS support 12.0

Sources/AnyImageKit/Core/Option/StringConfigKey.swift, Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Controller/PhotoPreviewController.swift, Sources/AnyImageKit/Picker/PickerOptionsInfo.swift, Sources/AnyImageKit/Picker/View/PickerPreviewIndexView.swift, Sources/AnyImageKit/Resources/Core/en.lproj/Core.strings, Sources/AnyImageKit/Resources/Core/pt-BR.lproj/Core.strings, Sources/AnyImageKit/Resources/Core/tr.lproj/Core.strings, Sources/AnyImageKit/Resources/Core/zh-Hans.lproj/Core.strings
=> Add clearSelectionAfterChangeAlbum

Sources/AnyImageKit/Picker/Controller/ImagePickerController.swift, Sources/AnyImageKit/Picker/Util/PickerManager.swift
=> fix(Picker): Sometimes cannot callback

Sources/AnyImageKit/Picker/Controller/AssetPickerViewController.swift, Sources/AnyImageKit/Picker/Model/Asset.swift
=> fix(Picker): memory leak when scrolling the picker

Sources/AnyImageKit/Capture/Controller/PadCaptureViewController.swift, Sources/AnyImageKit/Capture/Util/Recorder.swift, Sources/AnyImageKit/Core/Util/Common/FileHelper.swift, Sources/AnyImageKit/Core/Util/Common/ScreenHelper.swift, Sources/AnyImageKit/Core/Util/Export/ExportTool+PhotoURL.swift, Sources/AnyImageKit/Core/Util/Export/ExportTool+VideoURL.swift
=> Fix preferred output path
